cuentas/urls.py
from django.urls import path, include
from cuentas.views import registro, login_sesion, logout_sesion

app_name='cuentas'

urlpatterns = [
    path('registro/',registro,name="registro" ),
    path('login_sesion/',login_sesion,name="login"),
    path('',login_sesion,name="login"),
    path('logout/cuentas/',logout_sesion, name="logout"),
    #path('accounts/',include('django.contrib.auth.urls')),

    
]

gestion/api/urls.py
from django.urls import path, include,re_path
from .views import InicioListAPIView,InicioDetailAPIView,InicioUpdateAPIView,InicioDeleteAPIView,InicioCreateAPIView
from .views import PublicacionesListAPIView,PublicacionesDetailAPIView,PublicacionesUpdateAPIView,PublicacionesDeleteAPIView,PublicacionesCreateAPIView
from .views import PerfilListAPIView,PerfilDetailAPIView,PerfilUpdateAPIView

urlpatterns = [
    path('In/',InicioListAPIView.as_view(), name="listIn"),
    path('In/<int:pk>',InicioDeleteAPIView.as_view(), name="deleteIn"),
    path('In<int:pk>/',InicioDetailAPIView.as_view(), name="detailIn"),
    path('editarIn/<int:pk>/',InicioUpdateAPIView.as_view(), name="updateIn"),
    #path('eliminarIn/<int:pk>/',InicioDeleteAPIView.as_view(), name="deleteIn"),
    path('postearIn/',InicioCreateAPIView.as_view(), name="postearIn"),
    ##################################################################################
    path('Pu/',PublicacionesListAPIView.as_view(), name="listPu"),
    path('Pu/<int:pk>',PublicacionesDeleteAPIView.as_view(), name="deletePu"),
    path('Pu<int:pk>/',PublicacionesDetailAPIView.as_view(), name="detailPu"),
    path('editarPu/<int:pk>/',PublicacionesUpdateAPIView.as_view(), name="updatePu"),
    #path('eliminarPu/<int:pk>/',PublicacionesDeleteAPIView.as_view(), name="deletePu"),
    path('postearPu/',PublicacionesCreateAPIView.as_view(), name="postearPu"),
    ##################################################################################
    path('perfil/editarPer/',PerfilListAPIView.as_view(), name="listPer"),
    path('perfil/Per<int:pk>/',PerfilDetailAPIView.as_view(), name="detailPer"),
    path('perfil/editarPer/<int:pk>/',PerfilUpdateAPIView.as_view(), name="updatePer"),
    ]

gestion/urls.py
from django.urls import path, include
from gestion.views import historias,perfil, crear_perfil
from gestion.api.views import PerfilListAPIView,PerfilDetailAPIView,PerfilUpdateAPIView

app_name='gestion'

urlpatterns = [
    path('',historias, name="list"),
    path('perfil/',perfil, name="perfil"),
    path('crearPerfil/',crear_perfil, name="crearP"),
    path('api/perfil/editarPer/<int:pk>/',PerfilUpdateAPIView.as_view(), name="updatePer"),
    #path('accounts/',include('django.contrib.auth.urls')),
    ]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.routers import DefaultRouter
from gestion.views import PerfilViewSet


#router= DefaultRouter()
#router.register('gestion/api/publicar',InicioViewSet)
#router.register('gestion/api/editarperfil',PerfilViewSet)
#router.register('gestion/api/comentar',PublicacionesViewSet)


#urlpatterns = router.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cuentas.urls')),
    path('cuentas/',include('cuentas.urls')),
    path('gestion/',include('gestion.urls')),
    path('gestion/api/',include('gestion.api.urls')),
    path('',include('django.contrib.auth.urls')),
  
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class Inicio(models.Model):
    fecha=models.DateTimeField(auto_now_add=True)
    imagen=models.ImageField(upload_to='images_inicio/%Y/%m/%d/',blank=True, null=True)
    descripcion=models.CharField(max_length=100, blank=True, null=True)
    autor= models.ForeignKey(User,on_delete=models.CASCADE,default=None)

      
    def __str__(self):
        return str(self.imagen)

class Perfil(models.Model):
    autor= models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    nombre=models.CharField(max_length=100,blank=True, null=True)
    imagenPerfil=models.ImageField(upload_to='images_perfil/%Y/%m/%d/',blank=True,null=True)
    infoCuenta=models.CharField(max_length=100)
    

    def __str__(self):
        return str(self.autor)


class Publicaciones(models.Model):
    fecha=models.DateTimeField(auto_now_add=True)
    imagen=models.ForeignKey(Inicio,on_delete=models.CASCADE,default=None,blank=True,null=True)
    comentarios=models.CharField(max_length=100, blank=True, null=True)
    likes=models.PositiveIntegerField(validators=[MinValueValidator(1),MaxValueValidator(1)], blank=True, null=True)








     

gestion/forms.py
from django import forms
from .models import Perfil

class PerfilForm(forms.ModelForm):
    class Meta:
        model= Perfil
        fields= [
            'autor',
            'nombre',
            'imagenPerfil',
            'infoCuenta',

        ]

gestion/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView, DestroyAPIView,UpdateAPIView,CreateAPIView
from gestion.models import Inicio, Publicaciones, Perfil
from .serializers import InicioListSerializer,InicioDetailSerializer,InicioUpdateSerializer,InicioCreateSerializer
from .serializers import PublicacionesListSerializer,PublicacionesDetailSerializer,PublicacionesUpdateSerializer,PublicacionesCreateSerializer
from .serializers import PerfilListSerializer,PerfilDetailSerializer,PerfilUpdateSerializer

class InicioDetailAPIView(RetrieveAPIView):
    queryset= Inicio.objects.all()
    serializer_class= InicioDetailSerializer

class InicioUpdateAPIView(UpdateAPIView):
    queryset= Inicio.objects.all()
    serializer_class= InicioUpdateSerializer

class InicioDeleteAPIView(DestroyAPIView):
    queryset= Inicio.objects.all()
    serializer_class= InicioDetailSerializer

class InicioListAPIView(ListAPIView):
    queryset= Inicio.objects.all()
    serializer_class= InicioListSerializer
    lookup_field= 'pk'

class InicioCreateAPIView(CreateAPIView):
    queryset= Inicio.objects.all()
    serializer_class= InicioCreateSerializer

################################################################################
##################   COMENTARIOS- LIKES ########################################


class PublicacionesDetailAPIView(RetrieveAPIView):
    queryset= Publicaciones.objects.all()
    serializer_class= PublicacionesDetailSerializer

class PublicacionesUpdateAPIView(UpdateAPIView):
    queryset= Publicaciones.objects.all()
    serializer_class= PublicacionesUpdateSerializer

class PublicacionesDeleteAPIView(DestroyAPIView):
    queryset= Publicaciones.objects.all()
    serializer_class= PublicacionesDetailSerializer

class PublicacionesListAPIView(ListAPIView):
    queryset= Publicaciones.objects.all()
    serializer_class= PublicacionesListSerializer
    lookup_field= 'pk'

class PublicacionesCreateAPIView(CreateAPIView):
    queryset= Publicaciones.objects.all()
    serializer_class= PublicacionesCreateSerializer


################################################################################
##################   PERFIL ########################################

class PerfilDetailAPIView(RetrieveAPIView):
    queryset= Perfil.objects.all()
    serializer_class= PerfilDetailSerializer

class PerfilUpdateAPIView(UpdateAPIView):
    queryset=Perfil.objects.all()
    serializer_class= PerfilUpdateSerializer

class PerfilListAPIView(ListAPIView):
    queryset= Perfil.objects.all()
    serializer_class= PerfilListSerializer
    lookup_field= 'pk'
    

gestion/views.py
from django.shortcuts import render, redirect
from gestion.models import Inicio,Perfil, Publicaciones
from django.contrib.auth.models import User
from rest_framework import viewsets
from .serializers import PerfilSerializers
from django.db.models import Sum
from django.contrib.auth.decorators import login_required

from gestion.forms import PerfilForm

class PerfilViewSet(viewsets.ModelViewSet):
    serializer_class= PerfilSerializers
    queryset = Perfil.objects.all()

@login_required
def historias(request):
    posters= Inicio.objects.all().order_by('fecha')
    posters2= Publicaciones.objects.all()
    

    datos=[]
    for i in posters:
        var= i.id
        for j in posters2:
            var2=j.imagen_id
            if var==var2:
                var3=j.comentarios
                datos.append(dict([(var2,var3)]))
                print (datos)

    datoslikes=[]
    for i in posters:
        var= i.id
        for j in posters2:
            var2=j.imagen_id
            if var==var2:
                lik= Publicaciones.objects.filter(imagen_id=var).count()
                                                                #.aggregate(Sum('likes'))
                datoslikes.append(dict([(var2,lik)]))
                break   

                     
    context= {
        'posters':posters,
        'posters2':posters2,
        'datos': datos,
        'datoslikes': datoslikes,
    }

    return render(request,'gestion/historias_inicio.html',context)

@login_required    
def perfil(request):
    posters= Perfil.objects.all().order_by('-id')
    posters3=User.objects.order_by('-last_login').first()

    objeto1= Inicio.objects.all().order_by('fecha')

    for i in posters:
        var= i.autor
        if var == posters3:
            var5=i.autor_id
            posters4=Perfil.objects.all().filter(autor_id =var5)



    datos=[]
    for i in objeto1:
        var20= i.autor
        if var20==posters3:
            var30=i.imagen
            datos.append(dict([(var20,var30)]))

        print(datos)

    context= {
        'posters':posters,
        'posters3':posters3,
        'posters4':posters4,
        'datos': datos,

    }            
    return render(request,'gestion/plantilla_perfil.html',context)

        
def crear_perfil(request):
    form = PerfilForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        form= PerfilForm()
        return redirect('gestion:list')

    context = {
        'form': form
    }
    return render(request,'gestion/crear_perfil.html', context)


def Funcion_edit(request):
    return redirect('/gestion/api/perfil/editarPer/')

gestion/templates/gestion/crear_perfil.html
{% extends 'plantilla_base.html' %}

{% block title %}
  CREAR_PERFIL
{% endblock %}

{% block content %}
    <h1>CREACION DE PERFIL PERSONAL</h1>

    <form method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' action="/gestion/" value='CONTINUAR' />
    </form>

{% endblock %}

gestion/templates/gestion/historias_inicio.html
{% extends 'plantilla_base.html' %}

{% block title %}
  HISTORIAS
{% endblock %}

{% block content %}
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <a>Usuario activo:@{{user.username}}</a>
          </li>
          <form class="">
            <button type= "submit" name= boton_cerrar>
                <a href ="{% url 'logout' %}" style="color:black;"> Cerrar Sesion</a>
                
            </button>
          </form>
          {% endif %}
        </ul>
      <div>
      <form class="" action="/gestion/perfil/" method="get">
          <button type= "submit">
              VER PERFIL
          </button>
      </form>
  
      <form class="" action="/gestion/api/postearIn/" method="get">
        <button type= "submit">
            PUBLICAR FOTO
        </button>
    </form>

        
    <form class="" action="/gestion/api/In/" method="get">
      <button type= "submit">
          ELIMINAR PUBLICACION
      </button>
    </form> 
    
      <form class="" action="/gestion/api/postearPu/" method="get">
        <button type= "submit">
            COMENTAR FOTO
        </button>
      </form> 
    
      <form class="" action="/gestion/api/Pu/" method="get">
        <button type= "submit">
            ELIMINAR COMENTARIO
        </button>
      </form> 
    </div>
      </nav>
    </header>
    <h1>HISTORIAS DEL DIA...</h1>
    <div class="posters">
        {% for var in posters %}
          <div class="var">
            <p>@{{var.autor}}</p>
            <img src="{{ var.imagen.url}}" height="300" width="300"/>
            <p>Descripcion: {{var.descripcion}}</p>
            {% for datoL in datoslikes %}
              {% for id,lik in datoL.items %}
                {% if id == var.id %}
                  <p>Likes: {{lik}}</p>
                {% endif %}
              {% endfor %}
            {% endfor %}
            <p>Comentarios:</p>
            {% for dato in datos %}
              {% for id,coment in dato.items %}
                {% if id == var.id %}
                  <p>*{{coment}}</p>
                {% endif %}
              {% endfor %}
            {% endfor %}
            <p>{{var.fecha}}</p>
          </div>
        {% endfor %}
    </div>

{% endblock %}

gestion/templates/gestion/plantilla_perfil.html
{% extends 'plantilla_base.html' %}

{% block title %}
  PERFIL
{% endblock %}

{% block content %}
<header>
  <nav>
    <ul>
      {% if user.is_authenticated %}
      <li>
        <a>Usuario activo: {{user.username}}</a>
      </li>
      <form class="">
        <button type= "submit" name= boton_cerrar>
            <a href ="{% url 'logout' %}" style="color:black;"> Cerrar Sesion</a>
            
        </button>
      </form>
      {% endif %}
    </ul>

    <form class="" action="/gestion/" method="get">
      <button type= "submit">
          VER INICIO
      </button>
  </form>


  <form class="" action="/gestion/api/perfil/editarPer/" method="get">
    <button type= "submit">
        EDITAR PERFIL
    </button>
</form>

<a href = "{% url 'gestion:updatePer' user.id %}"></a>


  </nav>
</header>
    <h1>PERFIL PERSONAL</h1>
    <div class ="posters4">
      {% for var in posters4 %}
        {% if forloop.first %}
          <p>Usuario: @{{var.autor}}</p>
          <p>Nombre: {{var.nombre}}</p
          {% load static %}>
          <h2>Imagen de perfil.</h2>
          {% if var.imagenPerfil %}
            <img src="{{ var.imagenPerfil.url}}" height="300" width="300"/>
          {% else %}
            <img src="{%static 'sinFoto.jpg' %}" height="300" width="300"/>
          {% endif %}
          <p>Info. Cuenta: {{var.infoCuenta}}</p>
        {% endif %}

        <h2>PUBLICACIONES:</h2>
        {% for dato in datos %}
          {% for id,image in dato.items %}
              <img src="{{ image.url}}" height="300" width="300"/>
          {% endfor %}
        {% endfor %}
      {% endfor %}      
    </div>
{% endblock %}